events:
  world_boss:
    name: 'ワールドボス'
    time: '20_00'
  guild_boss:
    name: 'ギルドボス'
    time: '19_30'
  territory_war:
    name: '領土争奪戦'
    time: '20_30'
  vein_war:
    name: '鉱脈争奪戦'
    time: '21_00'
  crown_poker:
    name: 'クラウンポーカー'
    time: '19_30'
  guild_poker:
    name: 'ギルドポーカー'
  3vs3:
    name: '3:3天空リーグ'
    time: '21_00'
days:
  Mon: ['world_boss']
  Tue: ['guild_boss', 'world_boss']
  Wed: ['vein_war', 'guild_poker', 'world_boss']
  Thu: ['guild_boss', 'world_boss']
  Fri: ['crown_poker', 'world_boss']
  Sat: ['guild_boss', '3vs3', 'world_boss']
  Sun: ['territory_war', 'guild_poker', 'world_boss']
